config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    session: "sessions",
    registrations: "registrations"
  }

  authenticated :user, ->(user) { user.tech_admin? } do
    mount DelayedJobWeb, at: "/delayed_job"
  end

  devise_scope :user do
    delete "/sign_out" => "devise/sessions#destroy"
    get "/enter" => "registrations#new", as: :new_user_registration_path
  end

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  namespace :internal do
    resources :comments
    resources :articles
    resources :tags
    resources :welcome, only: %i[index create]
    resources :reactions, only: [:update]
    resources :broadcasts
    resources :pages
    resources :users do
      member do
        post "banish"
        post "full_delete"
        patch "user_status"
        post "merge"
      end
    end
    resources :classified_listings
    resources :listings, controller: "classified_listings"
    resources :events
    resources :dogfood, only: [:index]
    resources :buffer_updates, only: %i[create update]
    resources :articles, only: %i[index update] do
      get "rss_articles", on: :collection
    end
    resources :members, only: [:index]
    resources :events
    resources :feedback_messages, only: %i[update show]
    resources :reports, only: %i[index update show], controller: "feedback_messages" do
      collection do
        post "send_email"
        post "create_note"
        post "save_status"
      end
    end
  end

  namespace :api, defaults: { format: "json" } do
    scope module: :v0,
          constraints: ApiConstraints.new(version: 0, default: true) do
      resources :articles, only: %i[index show create update] do
        collection do
          get "/onboarding", to: "articles#onboarding"
        end
      end
      resources :comments
      resources :videos, only: [:index]
      resources :podcast_episodes, only: [:index]
      resources :reactions, only: [:create] do
        collection do
          post "/onboarding", to: "reactions#onboarding"
        end
      end
      resources :users, only: %i[index show] do
        collection do
          get "/sidebar_suggestions", to: "users#sidebar_suggestions"
        end
      end
      resources :tags, only: [:index] do
        collection do
          get "/onboarding", to: "tags#onboarding"
        end
      end
      resources :follows, only: [:create]
      resources :github_repos, only: [:index] do
        collection do
          post "/update_or_create", to: "github_repos#update_or_create"
        end
      end
      get "/analytics/totals", to: "analytics#totals"
      get "/analytics/historical", to: "analytics#historical"
      get "/analytics/past_day", to: "analytics#past_day"
    end
  end

  namespace :notifications do
    resources :counts, only: [:index]
    resources :reads, only: [:create]
  end

  resources :messages, only: [:create]
  resources :chat_channels, only: %i[index show create update]
  resources :chat_channel_memberships, only: %i[create update destroy]
  resources :articles, only: %i[update create destroy]
  resources :article_mutes, only: %i[update]
  resources :comments, only: %i[create update destroy]
  resources :comment_mutes, only: %i[update]
  resources :users, only: [:update] do
    resource :twitch_stream_updates, only: %i[show create]
  end
  resources :twitch_live_streams, only: :show, param: :username
  resources :reactions, only: %i[index create]
  resources :feedback_messages, only: %i[index create]
  get "/reports/:slug", to: "feedback_messages#show"
  resources :organizations, only: %i[update create]
  resources :followed_articles, only: [:index]
  resources :follows, only: %i[show create update]
  resources :giveaways, only: %i[create update]
  resources :image_uploads, only: [:create]
  resources :blocks
  resources :notifications, only: [:index]
  resources :tags, only: [:index]
  resources :stripe_active_cards, only: %i[create update destroy]
  resources :stripe_cancellations, only: [:create]
  resources :live_articles, only: [:index]
  resources :github_repos, only: %i[create update]
  resources :buffered_articles, only: [:index]
  resources :events, only: %i[index show]
  resources :additional_content_boxes, only: [:index]
  resources :videos, only: %i[index create new]
  resources :video_states, only: [:create]
  resources :twilio_tokens, only: [:show]
  resources :html_variants
  resources :html_variant_trials, only: [:create]
  resources :html_variant_successes, only: [:create]
  resources :push_notification_subscriptions, only: [:create]
  resources :tag_adjustments, only: [:create]
  resources :rating_votes, only: [:create]
  resources :page_views, only: %i[create update]
  resources :classified_listings, path: :listings, only: %i[index new create edit update delete]
  resources :credits, only: %i[index new create]
  resources :buffer_updates, only: [:create]
  resources :reading_list_items, only: [:update]

  get "/credits/purchase" => "credits#new"
  get "/listings/:category" => "classified_listings#index"
  get "/listings/:category/:slug" => "classified_listings#index"
  get "/listings/:category/:slug/:view" => "classified_listings#index",
      constraints: { view: /moderate/ }
  get "/notifications/:filter" => "notifications#index"
  get "/notifications/:filter/:org_id" => "notifications#index"
  patch "/onboarding_update" => "users#onboarding_update"
  get "email_subscriptions/unsubscribe"
  post "/chat_channels/:id/moderate" => "chat_channels#moderate"
  post "/chat_channels/:id/open" => "chat_channels#open"
  get "/connect" => "chat_channels#index"
  get "/connect/:slug" => "chat_channels#index"
  post "/chat_channels/create_chat" => "chat_channels#create_chat"
  post "/chat_channels/block_chat" => "chat_channels#block_chat"
  get "/live/:username" => "twitch_live_streams#show"

  post "/pusher/auth" => "pusher#auth"

  get "/social_previews/article/:id" => "social_previews#article", as: :article_social_preview
  get "/social_previews/user/:id" => "social_previews#user", as: :user_social_preview
  get "/social_previews/organization/:id" => "social_previews#organization", as: :organization_social_preview
  get "/social_previews/tag/:id" => "social_previews#tag", as: :tag_social_preview

  get "/async_info/base_data", controller: "async_info#base_data", defaults: { format: :json }

  get "/hello-goodbye-to-the-go-go-go",
      to: redirect("ben/hello-goodbye-to-the-go-go-go")
  get "/dhh-on-the-future-of-rails",
      to: redirect("ben/dhh-on-the-future-of-rails")
  get "/christopher-chedeau-on-the-philosophies-of-react",
      to: redirect("ben/christopher-chedeau-on-the-philosophies-of-react")
  get "/javascript-fatigue-buzzword",
      to: redirect("ben/javascript-fatigue-buzzword")
  get "/chris-seaton-making-ruby-fast",
      to: redirect("ben/chris-seaton-making-ruby-fast")
  get "/communicating-intent-the-perpetually-misunderstood-ruby-bang",
      to: redirect("tom/communicating-intent-the-perpetually-misunderstood-ruby-bang")
  get "/quick-tip-grepping-rails-routes",
      to: redirect("tom/quick-tip-grepping-rails-routes")
  get "/use-cases-for-githubs-new-direct-upload-feature",
      to: redirect("ben/use-cases-for-githubs-new-direct-upload-feature")
  get "/this-blog-post-was-written-using-draft-js",
      to: redirect("ben/this-blog-post-was-written-using-draft-js")
  get "/the-future-of-software-development",
      to: redirect("ben/the-future-of-software-development")
  get "/the-zen-of-missing-out-on-the-next-great-programming-tool",
      to: redirect("ben/the-zen-of-missing-out-on-the-next-great-programming-tool")
  get "/the-joy-and-benefit-of-being-an-early-adopter-in-programming",
      to: redirect("ben/the-joy-and-benefit-of-being-an-early-adopter-in-programming")
  get "/watkinsmatthewp/every-developer-should-write-a-personal-automation-api",
      to: redirect("anotherdevblog/every-developer-should-write-a-personal-automation-api")

  post "users/update_language_settings" => "users#update_language_settings"
  post "users/join_org" => "users#join_org"
  post "users/leave_org" => "users#leave_org"
  post "users/add_org_admin" => "users#add_org_admin"
  post "users/remove_org_admin" => "users#remove_org_admin"
  post "users/remove_from_org" => "users#remove_from_org"
  delete "users/remove_association", to: "users#remove_association"
  delete "users/destroy", to: "users#destroy"
  post "organizations/generate_new_secret" => "organizations#generate_new_secret"
  post "users/api_secrets" => "api_secrets#create"
  delete "users/api_secrets" => "api_secrets#destroy"

  get "/about" => "pages#about"
  get "/privacy" => "pages#privacy"
  get "/terms" => "pages#terms"
  get "/contact" => "pages#contact"
  get "/merch" => "pages#merch"
  get "/rlygenerator" => "pages#generator"
  get "/orlygenerator" => "pages#generator"
  get "/rlyslack" => "pages#generator"
  get "/rlyweb" => "pages#rlyweb"
  get "/rly" => "pages#rlyweb"
  get "/code-of-conduct" => "pages#code_of_conduct"
  get "/report-abuse" => "pages#report_abuse"
  get "/infiniteloop" => "pages#infinite_loop"
  get "/faq" => "pages#faq"
  get "/live" => "pages#live"
  get "/swagnets" => "pages#swagnets"
  get "/welcome" => "pages#welcome"
  get "/badge" => "pages#badge"
  get "/shecoded" => "pages#shecoded"
  get "/💸", to: redirect("t/hiring")
  get "/security", to: "pages#bounty"
  get "/survey", to: redirect("https://dev.to/ben/final-thoughts-on-the-state-of-the-web-survey-44nn")
  get "/now" => "pages#now"
  get "/events" => "events#index"
  get "/workshops", to: redirect("events")
  get "/sponsorship-info" => "pages#sponsorship_faq"
  get "/organization-info" => "pages#org_info"
  get "/sponsors" => "pages#sponsors"
  get "/search" => "stories#search"

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    def update
      user = User.find(params[:id])
      if user.errors.messages.blank? && user.update(user_params)
        flash[:notice] = "User successfully updated"
        redirect_to "/admin/users/#{params[:id]}"
      else
        render :new, locals: { page: Administrate::Page::Form.new(dashboard, user) }
      end
    end

    private

    def user_params
      accessible = %i[
        name
        email
        username
        twitter_username
        github_username
        profile_image
        website_url
        summary
        email_newsletter
        email_comment_notifications
        email_follower_notifications
        organization_id
        org_admin
        bg_color_hex
        text_color_hex
        employer_name
        employer_url
        employment_title
        currently_learning
        available_for
        mostly_work_with
        currently_hacking_on
        location
        email_public
        education
        feed_url
        reputation_modifier
        saw_onboarding
        scholar_email
        facebook_url
        behance_url
        dribbble_url
        medium_url
        gitlab_url
        linkedin_url
        twitch_url
      ]
      accessible << %i[password password_confirmation] if params[:user][:password].present?
      verify_usernames params.require(:user).permit(accessible)
    end

    # make sure usernames are not empty, to be able to use the database unique index
    def verify_usernames(user_params)
      user_params[:twitter_username] = nil if user_params[:twitter_username] == ""
      user_params[:github_username] = nil if user_params[:github_username] == ""
      user_params
    end
  end
end

app/controllers/api/v0/users_controller.rb
module Api
  module V0
    class UsersController < ApplicationController
      def index
        if !user_signed_in? || less_than_one_day_old?(current_user)
          usernames = %w[ben jess peter maestromac andy liana]
          @users = User.where(username: usernames)
          return
        end
        if params[:state] == "follow_suggestions"
          @users = Suggester::Users::Recent.new(current_user).suggest
        elsif params[:state] == "sidebar_suggestions"
          given_tag = params[:tag]
          @users = Suggester::Users::Sidebar.new(current_user, given_tag).suggest.sample(3)
        end
      end

      def show
        @user = if params[:id] == "by_username"
                  User.find_by(username: params[:url])
                else
                  User.find(params[:id])
                end
      end

      def less_than_one_day_old?(user)
        range = 1.day.ago.beginning_of_day..Time.current
        user_identity_age = user.github_created_at ||
          user.twitter_created_at || 8.days.ago
        # last one is a fallback in case both are nil
        range.cover? user_identity_age
      end
    end
  end
end

app/controllers/internal/application_controller.rb
class Internal::ApplicationController < ApplicationController
  before_action :authorize_admin

  private

  def authorize_admin
    authorize :admin, :minimal?
  end
end

app/controllers/internal/articles_controller.rb
class Internal::ArticlesController < Internal::ApplicationController
  layout "internal"

  def index
    @pending_buffer_updates = BufferUpdate.where(status: "pending").includes(:article)

    case params[:state]
    when /not\-buffered/
      days_ago = params[:state].split("-")[2].to_f
      @articles = Article.published.where(last_buffered: nil).
        where("published_at > ? OR crossposted_at > ?", days_ago.days.ago, days_ago.days.ago).
        includes(:user, :buffer_updates).
        limited_columns_internal_select.
        order("positive_reactions_count DESC").
        page(params[:page]).
        per(50)
    when /top\-/
      @articles = Article.published.
        where("published_at > ?", params[:state].split("-")[1].to_i.months.ago).
        includes(:user, :buffer_updates).
        limited_columns_internal_select.
        order("positive_reactions_count DESC").
        page(params[:page]).
        per(50)
    when "satellite"
      @articles = Article.published.where(last_buffered: nil).
        includes(:user, :buffer_updates).
        tagged_with(Tag.bufferized_tags, any: true).
        limited_columns_internal_select.
        order("hotness_score DESC").
        page(params[:page]).
        per(60)
    when "boosted-additional-articles"
      @articles = Article.boosted_via_additional_articles.
        includes(:user, :buffer_updates).
        limited_columns_internal_select.
        order("published_at DESC").
        page(params[:page]).
        per(100)
    when "chronological"
      @articles = Article.published.
        limited_columns_internal_select.
        order("published_at DESC").
        page(params[:page]).
        per(50)
    else # MIX
      @articles = Article.published.
        limited_columns_internal_select.
        order("hotness_score DESC").
        page(params[:page]).
        per(30)

      @featured_articles = Article.published.or(Article.where(published_from_feed: true)).
        where(featured: true).
        where("featured_number > ?", Time.current.to_i).
        includes(:user, :buffer_updates).
        limited_columns_internal_select.
        order("featured_number DESC")
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    article.featured = article_params[:featured].to_s == "true"
    article.approved = article_params[:approved].to_s == "true"
    article.live_now = article_params[:live_now].to_s == "true"
    article.email_digest_eligible = article_params[:email_digest_eligible].to_s == "true"
    article.boosted_additional_articles = article_params[:boosted_additional_articles].to_s == "true"
    article.boosted_dev_digest_email = article_params[:boosted_dev_digest_email].to_s == "true"
    article.user_id = article_params[:user_id].to_i

    article.update!(article_params)
    Article.where.not(id: article.id).where(live_now: true).update_all(live_now: false) if article.live_now
    CacheBuster.new.bust "/live_articles"
    # raise
    render body: nil
    # redirect_to "/internal/articles"
  end

  private

  def article_params
    params.require(:article).permit(:featured,
                                    :social_image,
                                    :body_markdown,
                                    :approved,
                                    :live_now,
                                    :email_digest_eligible,
                                    :boosted_additional_articles,
                                    :boosted_dev_digest_email,
                                    :main_image_background_hex_color,
                                    :featured_number,
                                    :user_id)
  end
end

app/controllers/internal/broadcasts_controller.rb
class Internal::BroadcastsController < Internal::ApplicationController
  layout "internal"

  def create
    @broadcast = Broadcast.new(broadcast_params)
    redirect_to "/internal/broadcasts"
  end

  def update
    @broadcast = Broadcast.find(params[:id])
    @broadcast.update(broadcast_params)
    redirect_to "/internal/broadcasts"
  end

  def new
    @broadcast = Broadcast.new
  end

  def edit
    @broadcast = Broadcast.find(params[:id])
  end

  def index
    @broadcasts = Broadcast.all
  end

  private

  def broadcast_params
    params.permit(:title, :processed_html, :type_of, :sent)
    # left out body_markdown and processed_html attributes
    #   until we decide we're using them
  end
end

app/views/internal/users/_activity.erb
<div class="row">
  <h3><u>Activity</u></h3>
  <ul>
    <li><%= @user.comments.size %> comments</li>
    <li><%= @user.articles.size %> articles</li>
    <li><%= @user.reactions.size %> reactions</li>
    <li><%= @user.followers.size %> followers</li>
    <li><%= @user.following_users_count %> users following</li>
    <li><%= @user.badge_achievements_count %> badges</li>
  </ul>
  <h3><u>Current Roles</u></h3>
  <p>(view full history in notes below)</p>
  <ul>
    <% @user.roles.each do |role| %>
      <li><%= role.name %> <em><%= "- " + Tag.find(role.resource_id).name if role.resource_id.present? %></em></li>
    <% end %>
  </ul>
</div>

app/views/internal/users/_credits.erb
<div class="row">
  <h3><u>Credits</u></h3>
  <p>Available User Credits: <%= @user.credits.where(spent: false).size %></p>
  <%= form_for [:internal, @user] do |f| %>
    <%= f.label "Add Credit(s): " %>
    <br>
    <%= f.text_field :add_credits, placeholder: "#" %>
    <br>
    <%= f.submit "Add Credits" %>
  <% end %>
  <%= form_for [:internal, @user] do |f| %>
    <%= f.label "Remove Credits(s)" %>
    <br>
    <%= f.text_field :remove_credits, placeholder: "#" %>
    <br>
    <%= f.submit "Remove Credits"%>
  <% end %>
  <br>
  <% if @user.organization_id %>
    <p>Available <%= Organization.find(@user.organization_id).name %> Credits: <%= Organization.find(@user.organization_id).credits.where(spent: false).size %></p>
    <%= form_for [:internal, @user] do |f| %>
      <%= f.label "Add Org Credit(s): " %>
      <br>
      <%= f.text_field :add_org_credits, placeholder: "#" %>
      <br>
      <%= f.submit "Add Org Credits" %>
    <% end %>
    <%= form_for [:internal, @user] do |f| %>
      <%= f.label "Remove Org Credits(s)" %>
      <br>
      <%= f.text_field :remove_org_credits, placeholder: "#" %>
      <br>
      <%= f.submit "Remove Org Credits"%>
    <% end %>
  <% end %>
</div>

app/views/internal/users/edit.html.erb
<h1>
  <%= @user.name %><a href="/<%= @user.username %>" target="_blank"> (@<%= @user.username %>)</a>
</h1>
<p>
  <u><a style="color: green" href="/internal/users/<%= @user.id %>">click here view user details & take other actions</a></u>
</p>
<p><em>Member since <%= @user.created_at.strftime("%b %e '%y") %></em></p>
<%= render "internal/users/activity" %>
<div class="row">
  <h2>User Status</h2>
  <% if @user.banned %>
    <p style="background-color:red;color:white">🚨 Member is suspended 🚨</p>
  <% elsif @user.warned %>
    <p style="background-color: orange;color:white">Member is warned</p>
  <% elsif @user.comment_banned %>
    <p style="background-color: orange;color:white">Member is comment banned</p>
  <% elsif @user.trusted %>
    <p style="background-color: green;color:white">Member is trusted</p>
  <% else %>
    <p style="color:green">Member is in good standing</p>
  <% end %>
  <p><strong>Current Roles</strong><em> (view full history in notes below)</em>:</p>
  <ul>
    <% if @user.roles.empty? %>
      <li>Regular Member</li>
    <% end %>
    <% @user.roles.each do |role| %>
        <li><%= role.name %> <em><%= "- " + Tag.find(role.resource_id).name if role.resource_id.present? %></em></li>
    <% end %>
  </ul>
  <%= form_for(@user, url: user_status_internal_user_path(@user)) do |f| %>
    <%= f.label "Select new user status" %>
    <%= f.select(:user_status, options_for_select(["Warn", "Comment Ban", "Ban", "Regular Member", "Trusted", "Pro"]), include_blank: true) %>
    <br>
    <%= f.label "Reason for action:" %>
    <%= f.text_area :note_for_current_role, required: true %>
    <br>
    <%= f.submit "Update User Status" %>
  <% end %>
</div>
<%= render "notes" %>
<div class="row">
  <h2>Merge User</h2>
  <p>To merge a duplicate account, make sure you are currently on the page of the user you want to KEEP. Below, add the user id of the account to merge information from, and delete.</p>
  <%= form_for(@user, url: merge_internal_user_path(@user), html: { method: :post, onsubmit: "return confirm('Are you sure? This is extremely destructive and irreversible. Merging will delete all the other users content and combine it with this user')" }) do |f| %>
    <%= f.label "User to be deleted:" %>
    <%= f.text_field :merge_user_id, placeholder: "#ID" %>
    <%= f.submit "Merge Users" %>
  <% end %>
</div>
<div class="row">
  <h2>Banish User</h2>
  <% if @user.banished? %>
    <p>User has been banished.</p>
  <% elsif @user.comments.where("created_at < ?", 100.days.ago).empty? && @user.created_at < 100.days.ago %>
    <p>
      <em>This is extremely destructive. Banishing will delete all the user's existing content and change their username to @spam_###.</em>
    </p>
    <p><strong>Do not do this lightly.</strong></p>
    <%= form_for(@user, url: banish_internal_user_path(@user), html: { method: :post, onsubmit: "return confirm('Are you sure? This is extremely destructive and irreversible. Banishing will delete all articles and turn their username into @spam_###')" }) do %>
      <button class="btn btn-danger" style="font-size:2em;">🚫 Banish User for Spam 🚫</button>
    <% end %>
  <% elsif current_user.has_role?(:super_admin) %>
    <p><strong>This is not a new user.</strong> You are only allowed to take this action because you are a
      <strong>super admin.</strong></p>
    <p>
      <em>This is extremely destructive. Banishing will delete all the user's existing content and change their username to @spam_###.</em>
    </p>
    <p><strong>Do not do this lightly.</strong></p>
    <%= form_for(@user, url: banish_internal_user_path(@user), html: { method: :post, onsubmit: "return confirm('Are you sure? This is extremely destructive and irreversible. Banishing will delete all articles and turn their username into @spam_###')" }) do %>
      <button class="btn btn-danger" style="font-size:2em;">Banish User for Spam!</button>
    <% end %>
  <% else %>
    <p><em>This is not a new user so you'll need to contact a super admin to banish this user.</em></p>
  <% end %>
</div>

<div class="row">
  <h2>Delete User & Turn Content Into Ghost</h2>
  <% if current_user.has_role?(:super_admin) %>
    <p>This will
      <strong>completely destroy the user</strong> and convert all of their articles & comments into a ghost author. This action is irreversible.
    </p>
    <p><strong>Do not do this lightly.</strong></p>
    <%= form_for(@user, url: full_delete_internal_user_path(@user), html: { method: :post, onsubmit: "return confirm('Are you sure? 👻 This is extremely destructive and irreversible. The user will be deleted and their articles & comments will be converted to Ghost')" }) do |f| %>
      <%= f.hidden_field :ghostify, value: true %>
      <button class="btn btn-danger" style="font-size:2em;">👻 Fully Delete User & Ghostify 👻</button>
    <% end %>
  <% else %>
    <p>Only super admins can fully delete users.</p>
  <% end %>
</div>

<div class="row">
  <h2>Fully Delete User</h2>
  <% if current_user.has_role?(:super_admin) %>
    <p>This will
      <strong>completely destroy the user</strong> and all of their activity from our database. This action is irreversible.
    </p>
    <p><strong>Do not do this lightly.</strong></p>
    <%= form_for(@user, url: full_delete_internal_user_path(@user), html: { method: :post, onsubmit: "return confirm('Are you sure? This is extremely destructive and irreversible.')" }) do |f| %>
    <%= f.hidden_field :ghostify, value: false %>
      <button class="btn btn-danger" style="font-size:2em;">☠️ Fully Delete User & All Activity ☠️</button>
    <% end %>
  <% else %>
    <p>Only super admins can fully delete users.</p>
  <% end %>
</div>
<br>
<br>

app/views/internal/users/show.html.erb
<style>
  dt {
    width: calc(20% - 1rem);
    float: left;
  }

  dd {
    width: calc(80% - 1rem)
  }
</style>
<div class="row">
  <h1>
    <%= @user.name %><a href="/<%= @user.username %>" target="_blank"> (@<%= @user.username %>)</a>
  </h1>
  <p><u><a style="color: red" href="/internal/users/<%= @user.id %>/edit">click here to merge, banish, or delete user.</a></u>
  </p>
  <p><em>Member since <%= @user.created_at.strftime("%b %e '%y") %></em></p>
  <p><strong><u>General Info</u></strong></p>
  <dl>
    <dt>ID:</dt>
    <dd><%= @user.id %></span></dd>
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
    <dt>Name:</dt>
    <dd><%= @user.name %></dd>
    <dt>Email:</dt>
    <dd><%= @user.email %></dd>
    <dt>Twitter:</dt>
    <dd><%= @user.twitter_username || "N/A" %></dd>
    <dt>GitHub:</dt>
    <dd><%= @user.github_username || "N/A" %></dd>
    <dt>Sustaining Member:</dt>
    <dd><%= @user.a_sustaining_member? %></dd>
    <% if @user.a_sustaining_member? %>
      <dt>Monthly Dues:</dt>
      <dd><%= @user.monthly_dues %></dd>
      <dt>25% Off Coupon:</dt>
      <dd><%= CouponGenerator.new(current_user.id, "member_discount").generate %> || "N/A" </dd>
      <dt>1x Gift:</dt>
      <dd><%= CouponGenerator.new(current_user.id, "tee_pack").generate %> || "N/A" </dd>
    <% end %>
  </dl>
</div>
<%= render "activity" %>
<%= render "credits" %>
<div class="row">
  <h3><u>Mentorship</u></h3>
  <% if @user.mentors.count > 0 %>
    <h4> Mentor(s):</h4>
    <ul>
      <% @user_mentor_relationships.each do |relationship| %>
        <li>
          <a href="https://dev.to/<%= User.find(relationship.mentor_id).username %>" target=">blank">@<%= User.find(relationship.mentor_id).username %></a>
          <% if relationship.active %>
            <span style="color:green"><em> (active)</em></span>
          <% else %>
            <span style="color:red"><em> (inactive)</em></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% elsif @user.mentees.count > 0 %>
    <h4>Mentee(s):</h4>
    <ul>
      <% @user_mentee_relationships.each do |relationship| %>
        <li>
          <a href="https://dev.to/<%= User.find(relationship.mentee_id).username %>" target=">blank">@<%= User.find(relationship.mentee_id).username %></a>
          <% if relationship.active %>
            <span style="color:green"><em> (active)</em></span>
          <% else %>
            <span style="color:red"><em> (inactive)</em></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% elsif @user.has_role? :banned_from_mentorship %>
    <p style="background-color: red;">User is banned from the mentorship program.</p>
  <% else %>
    <p>Currently not in a mentorship relationship.</p>
  <% end %>
  <%= form_for(@user, url: user_status_internal_user_path(@user)) do |f| %>
    <p>Ban from mentorship: <%= f.check_box :toggle_mentorship, checked: @user.has_role?(:banned_from_mentorship) %></p>
    <p>Reason for action: <%= f.text_area :mentorship_note %></p>
    <%= f.submit %>
  <% end %>
</div>
<%= render "notes" %>
<%= render "mentee_match" %>
<div class="row">
  <h2><u>Recent Emails</u></h2>
  <ul>
    <% @user.email_messages.order("sent_at DESC").limit(50).each do |email| %>
      <li><a href="/admin/email_messages/<%= email.id %>"><%= email.subject %></a>
        <em><%= email.sent_at&.strftime("%b %e '%y") %></em></li>
    <% end %>
  </ul>
</div>
<br>
<br>